#ifndef CAN_COMMANDS_H
#define CAN_COMMANDS_H

typedef enum {
    CMD_SET_ESTOP,
    CMD_SET_ADDRESS,
    CMD_SET_STATE,
    CMD_SET_INPUT_TORQUE,
    CMD_SET_INPUT_SPEED,
    CMD_SET_INPUT_POSITION,
    CMD_SET_LIMITS,
    CMD_SET_REQUEST,
    CMD_GET_PING,
    CMD_GET_HEARTBEAT,
    CMD_GET_ERROR,
    CMD_GET_STATUS
} CommandTypeDef;


#endif // CAN_COMMANDS_H