#ifndef FOC_H
#define FOC_H

#include "main.h"

typedef enum {
    FOC_STATE_INIT,
    FOC_STATE_BOOTUP_SOUND,
    FOC_STATE_CURRENT_SENSOR_CALIBRATION,
    FOC_STATE_IDENTIFY,
    FOC_STATE_ANTICOGGING,
    FOC_STATE_CHECKLIST,
    FOC_STATE_PID_AUTOTUNE,
    FOC_STATE_GENERAL_TEST,
    FOC_STATE_ERROR,
    FOC_STATE_CALIBRATION,
    FOC_STATE_ALIGNMENT,
    FOC_STATE_ALIGNMENT_TEST,
    FOC_STATE_RUN,
    FOC_STATE_FLASH_SAVE,
    FOC_STATE_OPENLOOP
} FOC_State;


void FOC_Setup();
void FOC_Loop();

#endif // FOC_H